[[redirects]]
  from = "/speak"
  to = "https://forms.gle/LP9eHToXeds7GzrXA"
  status = 301

[[redirects]]
  from = "/feedback"
  to = "https://forms.gle/PgP5UqqBvTYkJBPx8"
  status = 301

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
